source 'https://rubygems.org'

ruby '2.2.0'

gem 'bundler', '~> 1.7.9'

gem 'pry',                '= 0.10.1'
gem 'pry-nav',            '= 0.2.4'
gem 'pry-rescue',         '~> 1.4.1'
gem 'pry-stack_explorer', '= 0.4.9.2'
gem 'rake',               '~> 10.4.2'
gem 'rspec',              '~> 3.1.0'
